FROM ruby:2.4.2
ENV LANG C.UTF-8

# 必要なパッケージだけインストールして余計なものは削除
RUN apt-get update -qq \
  && apt-get install -y --no-install-recommends build-essential nodejs \
  && apt-get clean \
  && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*

# メインプロセス実行前に複数のコマンド実行をしたいのでprehookを利用する
ENV ENTRYKIT_VERSION 0.4.0
RUN wget https://github.com/progrium/entrykit/releases/download/v${ENTRYKIT_VERSION}/entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
  && tar -xvzf entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
  && rm entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
  && mv entrykit /bin/entrykit \
  && chmod +x /bin/entrykit \
  && entrykit --symlink

RUN mkdir -p /myapp
WORKDIR /myapp

ENTRYPOINT [ \
  "prehook", "ruby -v", "--", \
  "prehook", "bundle install --jobs 3", "--"]
