version: '3'
services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
      - bundle-install:/usr/local/bundle
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  spring:
    <<: *app
    command: ["bundle", "exec", "spring", "server"]
    ports: []
volumes:
  bundle-install:
    driver: local
  db-data:
    driver: local
