#!/usr/bin/env bash

docker-compose build
docker-compose run --rm app rails new . --force --database=mysql --skip-bundle --skip-coffee --skip-turbolinks
cp -rf template/ .
mkdir -p frontend/javascripts
docker-compose run --rm app bundle exec spring binstub --all
